# Describes the format for available image processing services

scan:
  description: Process an image immediately.
  fields:
    entity_id:
      description: Name(s) of entities to scan immediately.
      example: 'image_processing.alpr_garage'

teach:
  description: Teach a classifier a name.
  fields:
    entity_id:
      description: The image processing entity to teach.
      example: 'image_processing.facebox'
    name:
      description: The name to teach.
      example: 'my_name'
    file_path:
      description: Path to the image file.
      example: '/images/my_image.jpg'
